"""Phase 6: evidence-grounded Intelligence Copilot orchestration.

The LLM, when available, is only asked to explain a compact context selected
by deterministic routing. Numeric evidence and navigation actions are owned by
the application, not generated by the model.
"""
from __future__ import annotations

import json
import os
import re
from datetime import datetime, time
from typing import Any

import requests
from sqlalchemy import func
from sqlalchemy.orm import Session

from .models import Incident, Ward
from .intelligence_brief import generate_intelligence_brief
from .prediction import predict_risk
from .trend_analysis import analyze_trends
from .alert_engine import generate_alerts
from .analytics import detect_hotspots
from .network_analysis import build_network

INTENTS = ("SUMMARY", "RISK", "TREND", "ALERT", "HOTSPOT", "NETWORK", "OFFENDER", "INCIDENT", "COMPARE", "FOLLOW_UP", "GENERAL_ANALYTICS", "OUT_OF_SCOPE")
SUPPORTED_ACTIONS = {"view_brief", "view_district", "view_ward", "view_trend", "view_risk", "view_alerts", "view_hotspots", "view_network"}


def route_intent(message: str) -> str:
    q = message.lower()
    if any(x in q for x in ("cricket", "football", "weather", "stock price", "recipe", "movie review")): return "OUT_OF_SCOPE"
    if any(x in q for x in ("compare", "versus", " vs ", "difference between")): return "COMPARE"
    if "which ward" in q and any(x in q for x in ("attention", "priority", "focus")): return "SUMMARY"
    if any(x in q for x in ("why", "what should i inspect", "next", "follow-up")) and "alert" not in q and "risk" not in q:
        return "FOLLOW_UP" if any(x in q for x in ("inspect", "next", "follow-up")) else "RISK"
    if any(x in q for x in ("risk", "predict", "future", "attention", "priority", "high risk")): return "RISK"
    if any(x in q for x in ("trend", "changed", "change", "rising", "increasing", "baseline", "anomal")): return "TREND"
    if any(x in q for x in ("alert", "warning")): return "ALERT"
    if any(x in q for x in ("hotspot", "cluster", "where")): return "HOTSPOT"
    if any(x in q for x in ("network", "connected", "connector", "community", "linked")): return "NETWORK"
    if any(x in q for x in ("offender", "accused", "repeat")): return "OFFENDER"
    if any(x in q for x in ("incident", "happened", "recent", "latest")): return "INCIDENT"
    if any(x in q for x in ("summar", "important", "intelligence picture", "what's here", "what is here")): return "SUMMARY"
    return "GENERAL_ANALYTICS"


def _dates(context: dict) -> tuple[datetime | None, datetime | None]:
    def parse(value, end_of_day=False):
        try:
            parsed = datetime.fromisoformat(value) if value else None
            if parsed and end_of_day and "T" not in value and " " not in value:
                return datetime.combine(parsed.date(), time.max)
            return parsed
        except (TypeError, ValueError): return None
    return parse(context.get("date_from")), parse(context.get("date_to"), end_of_day=True)


def _scope(context: dict) -> tuple[str | None, int | None, str | None]:
    district = context.get("district") or context.get("selectedDistrict")
    ward_id = context.get("ward_id")
    if ward_id is None and isinstance(context.get("selectedWard"), dict): ward_id = context["selectedWard"].get("id")
    crime = context.get("crime_type") or context.get("selectedCrimeType")
    return district or None, int(ward_id) if ward_id is not None else None, crime or None


def _action(label: str, action: str, **extra) -> dict:
    return {"label": label, "action": action, **extra} if action in SUPPORTED_ACTIONS else {}


def _brief_context(db, district, ward_id, crime, date_from, date_to, horizon, granularity):
    return generate_intelligence_brief(db, district=district, ward_id=ward_id, crime_type=crime,
                                       date_from=date_from, date_to=date_to, horizon_days=horizon,
                                       granularity=granularity)


def _compact(data: Any, limit: int = 9000):
    if not data:
        return None
    serialized = json.dumps(data, default=str, allow_nan=False)
    if len(serialized) <= limit:
        return json.loads(serialized)
    if isinstance(data, dict):
        compact = {k: data[k] for k in ("status", "summary", "params", "scope", "priority", "headline", "key_development", "predictive_risk", "alerts", "hotspots", "network", "why_it_matters", "analytical_followups") if k in data}
        return json.loads(json.dumps(compact, default=str, allow_nan=False))
    return {"truncated": True, "summary": f"{len(data)} records available; only a compact analytical summary was supplied."}


def build_evidence_context(db: Session, message: str, context: dict) -> dict:
    intent = route_intent(message)
    district, ward_id, crime = _scope(context)
    date_from, date_to = _dates(context)
    horizon = int(context.get("prediction_horizon") or context.get("horizonDays") or 14)
    granularity = context.get("granularity") or context.get("trendGranularity") or "weekly"
    base = {"intent": intent, "scope": {"district": district, "ward_id": ward_id, "crime_type": crime}, "sources": []}

    if intent in ("SUMMARY", "FOLLOW_UP", "GENERAL_ANALYTICS"):
        brief = _brief_context(db, district, ward_id, crime, date_from, date_to, horizon, granularity)
        base.update({"brief": _compact(brief), "sources": ["Intelligence Brief"]})
        return base
    if intent == "OUT_OF_SCOPE":
        base.update({"sources": []})
        return base
    if intent == "RISK":
        risk = predict_risk(db, district=district, ward_id=ward_id, crime_type=crime, horizon_days=horizon, as_of=date_to)
        base.update({"risk": _compact(risk), "sources": ["Predictive Risk"]})
        return base
    if intent == "TREND":
        trend = analyze_trends(db, district=district, ward_id=ward_id, crime_type=crime, date_from=date_from, date_to=date_to, granularity=granularity)
        base.update({"trend": _compact(trend), "sources": ["Trend Analytics"]})
        return base
    if intent == "ALERT":
        alerts = generate_alerts(db, district=district, ward_id=ward_id, crime_type=crime, date_from=date_from, date_to=date_to, granularity=granularity)
        base.update({"alerts": _compact(alerts), "sources": ["Intelligence Alerts"]})
        return base
    if intent == "HOTSPOT":
        base.update({"hotspots": _compact(detect_hotspots(db, district=district, crime_type=crime, date_from=date_from, date_to=date_to)), "sources": ["Hotspot Analytics"]})
        return base
    if intent in ("NETWORK", "OFFENDER"):
        network = build_network(db, ward_id=ward_id, district=district, crime_type=crime, date_from=date_from, date_to=date_to)
        if intent == "OFFENDER":
            network = {"summary": network.get("summary"), "nodes": [n for n in network.get("nodes", []) if n.get("incident_count", 0) > 1][:8]}
        base.update({"network": _compact(network), "sources": ["Network Analytics", "Repeat Offender Analytics"]})
        return base
    if intent == "INCIDENT":
        q = db.query(Incident).order_by(Incident.timestamp.desc()).limit(5)
        if district: q = q.filter(Incident.district == district)
        if ward_id is not None: q = q.filter(Incident.ward_id == ward_id)
        if crime: q = q.filter(Incident.crime_type == crime)
        incidents = [{"id": i.id, "timestamp": i.timestamp.isoformat(), "crime_type": i.crime_type, "severity": i.severity, "district": i.district, "ward_id": i.ward_id} for i in q.all()]
        base.update({"incidents": incidents, "sources": ["Incident Records"]})
        return base
    return base


def _find_compare_wards(db: Session, message: str, district: str | None) -> list[Ward]:
    wards = db.query(Ward).filter(Ward.district == district).all() if district else db.query(Ward).all()
    q = message.lower()
    matches = [w for w in wards if w.name.lower() in q]
    return matches[:2] if len(matches) >= 2 else []


def _fallback(message: str, evidence: dict, db: Session) -> tuple[str, list[dict]]:
    intent, scope = evidence["intent"], evidence["scope"]
    name = scope.get("district") or "the selected scope"
    actions = []
    if intent in ("SUMMARY", "FOLLOW_UP", "GENERAL_ANALYTICS"):
        b = evidence.get("brief") or {}
        if b.get("status") == "selection_required":
            return "Select a district or ward first so I can ground the summary in the available intelligence analytics.", []
        p = b.get("priority", {})
        answer = f"{b.get('scope', {}).get('name', name)} has {p.get('level', 'available')} priority ({p.get('score', '—')}/100). {b.get('headline', 'No consolidated intelligence brief is available.') }"
        if b.get("why_it_matters"): answer += " " + " ".join(b["why_it_matters"][:2])
        actions = b.get("analytical_followups", [])
    elif intent == "RISK":
        ps = (evidence.get("risk") or {}).get("predictions", [])
        p = ps[0] if ps else None
        answer = (f"The model estimates {p['risk_score']}/100 {p['risk_level'].upper()} risk over the next {p['prediction_horizon_days']} days." if p and not p.get("insufficient_data") else "There is not enough historical data to generate a reliable prediction for this scope.")
        actions = [_action("View Risk", "view_risk")]
    elif intent == "TREND":
        t = evidence.get("trend") or {}; candidates = t.get("anomalies") or t.get("top_emerging_trends") or []
        top = max(candidates, key=lambda x: abs(x.get("percentage_change", x.get("change_percent", 0)) or 0), default=None)
        answer = "No significant trend anomaly was detected for this scope." if not top else f"{top.get('crime_type') or 'Crime'} is showing a {top.get('direction', 'rising')} signal with a {top.get('percentage_change', top.get('change_percent', '—'))}% change."
        actions = [_action("View Trend", "view_trend")]
    elif intent == "ALERT":
        a = evidence.get("alerts") or {}; s = a.get("summary", {})
        answer = f"There are {s.get('total', 0)} active intelligence alerts in this scope, including {s.get('critical', 0)} critical and {s.get('high', 0)} high-severity alerts."
        actions = [_action("View Alerts", "view_alerts")]
    elif intent == "HOTSPOT":
        h = evidence.get("hotspots") or {}; answer = f"{h.get('n_clusters', 0)} active hotspot clusters were detected from {h.get('n_incidents', 0)} incidents."; actions = [_action("View Hotspots", "view_hotspots")]
    elif intent in ("NETWORK", "OFFENDER"):
        n = evidence.get("network") or {}; s = n.get("summary") or {}; answer = f"The network contains {s.get('n_nodes', 0)} linked offenders across {s.get('n_communities', 0)} communities."; actions = [_action("Open Network", "view_network")]
    elif intent == "INCIDENT":
        rows = evidence.get("incidents") or []; answer = "No recent incidents were found." if not rows else "Recent records: " + "; ".join(f"{r['crime_type']} ({r['severity']}/10)" for r in rows[:3])
    elif intent == "COMPARE":
        rows = evidence.get("comparison") or []
        ranked = sorted(rows, key=lambda x: (x.get("brief", {}).get("priority", {}).get("score") or -1), reverse=True)
        if not ranked:
            answer = "I could not reliably identify two wards to compare."
        else:
            answer = "Comparison: " + "; ".join(f"{x['ward']} has {x.get('brief', {}).get('priority', {}).get('level', 'unavailable')} priority ({x.get('brief', {}).get('priority', {}).get('score', '—')}/100)" for x in ranked)
            top = ranked[0]; scope = evidence.get("scope", {})
            actions = [_action(f"Open {top['ward']}", "view_ward", ward_id=top.get("brief", {}).get("scope", {}).get("ward_id"), ward_name=top["ward"], district=scope.get("district"))]
    elif intent == "OUT_OF_SCOPE":
        answer = "The Intelligence Copilot is designed for the Crime Intel Suite analytical dataset. I can help with risk, trends, alerts, hotspots, incidents, offenders, networks, and intelligence briefs."
    else:
        answer = "The Intelligence Copilot is designed for this crime analytics dataset. Ask about risk, trends, alerts, hotspots, incidents, offenders, networks, or the current intelligence brief."
    return answer, [a for a in actions if a]


def _call_llm(message: str, evidence: dict, history: list[dict]) -> str | None:
    key = os.getenv("OPENAI_API_KEY")
    if not key: return None
    body = {"model": os.getenv("OPENAI_MODEL", "llama-3.3-70b-versatile"), "messages": [
        {"role": "system", "content": "You are Intelligence Copilot for Crime Intel Suite. Use only the supplied structured evidence. Never invent numbers, people, locations, causes, certainty, or enforcement recommendations. Distinguish predictions from observed trends. Be concise (2-5 sentences). If evidence is missing, say so."},
        *[{"role": x.get("role", "user"), "content": str(x.get("content", ""))[:1200]} for x in history[-8:]],
        {"role": "user", "content": f"Evidence context (authoritative):\n{json.dumps(evidence, ensure_ascii=False, default=str)[:10000]}\n\nQuestion: {message}"},
    ], "temperature": 0.1, "max_tokens": 350}
    try:
        response = requests.post(f"{os.getenv('OPENAI_BASE_URL', 'https://api.groq.com/openai/v1')}/chat/completions", headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json", "User-Agent": "CrimeIntelSuite/1.0"}, json=body, timeout=20)
        response.raise_for_status()
        return response.json()["choices"][0]["message"]["content"].strip()
    except Exception:
        return None


def answer_copilot(db: Session, message: str, context: dict | None = None, history: list[dict] | None = None) -> dict:
    context = context or {}; history = history or []
    evidence = build_evidence_context(db, message, context)
    if evidence["intent"] == "COMPARE":
        district, _, crime = _scope(context); wards = _find_compare_wards(db, message, district)
        if len(wards) < 2:
            return {"answer": "I could not reliably identify two wards to compare. Include both ward names from the selected district.", "evidence": [], "actions": [], "scope": {"district": district, "ward_id": None}, "sources": []}
        briefs = [_brief_context(db, district, w.id, crime, *_dates(context), int(context.get("prediction_horizon") or 14), context.get("granularity") or "weekly") for w in wards]
        evidence.update({"comparison": [{"ward": w.name, "brief": _compact(b)} for w, b in zip(wards, briefs)], "sources": ["Ward Intelligence Briefs"]})
    fallback, actions = _fallback(message, evidence, db)
    answer = _call_llm(message, evidence, history) or fallback
    # The model never controls these fields; they are application-derived.
    sources = evidence.get("sources", [])
    return {"answer": answer, "evidence": _evidence_rows(evidence), "actions": [a for a in actions if a.get("action") in SUPPORTED_ACTIONS], "scope": evidence["scope"], "sources": sources, "intent": evidence["intent"]}


def _evidence_rows(evidence: dict) -> list[dict]:
    rows = []
    b = evidence.get("brief") or {}
    if b.get("predictive_risk", {}).get("risk_score") is not None:
        p = b["predictive_risk"]; rows.append({"label": "Predictive risk", "value": f"{p['risk_score']}/100 — {str(p.get('risk_level', '')).upper()}"})
    if b.get("key_development"):
        t = b["key_development"]; rows.append({"label": "Trend", "value": f"{t.get('crime_type') or 'Crime'} {t.get('change_percent')}% — {t.get('severity')}"})
    if b.get("alerts", {}).get("total") is not None: rows.append({"label": "Active alerts", "value": str(b["alerts"]["total"])})
    if b.get("hotspots", {}).get("count") is not None: rows.append({"label": "Hotspots", "value": str(b["hotspots"]["count"])})
    if evidence.get("risk", {}).get("predictions"):
        p = evidence["risk"]["predictions"][0]
        rows.append({"label": "Predictive risk", "value": "Insufficient historical data" if p.get("insufficient_data") else f"{p.get('risk_score')}/100 — {str(p.get('risk_level', '')).upper()}"})
    if evidence.get("trend"):
        t = evidence["trend"]; candidates = t.get("anomalies") or t.get("top_emerging_trends") or []
        top = max(candidates, key=lambda x: abs(x.get("percentage_change", x.get("change_percent", 0)) or 0), default=None)
        if top:
            rows.append({"label": "Trend", "value": f"{top.get('crime_type') or 'Crime'} {top.get('percentage_change', top.get('change_percent', '—'))}% — {str(top.get('severity') or top.get('direction') or '').upper()}"})
    if evidence.get("hotspots"):
        h = evidence["hotspots"]; rows.append({"label": "Hotspots", "value": f"{h.get('n_clusters', 0)} clusters from {h.get('n_incidents', 0)} incidents"})
    if evidence.get("alerts", {}).get("summary"):
        s = evidence["alerts"]["summary"]; rows.append({"label": "Alerts", "value": f"{s.get('total', 0)} total; {s.get('critical', 0)} critical"})
    if evidence.get("network", {}).get("summary"):
        s = evidence["network"]["summary"]; rows.append({"label": "Network", "value": f"{s.get('n_nodes', 0)} linked offenders; {s.get('n_communities', 0)} communities"})
    if evidence.get("comparison"):
        for item in evidence["comparison"][:2]:
            b = item.get("brief", {}); rows.append({"label": item.get("ward", "Ward"), "value": f"{b.get('priority', {}).get('score', '—')}/100 {b.get('priority', {}).get('level', 'unavailable')} · {b.get('summary', {}).get('incidents', b.get('recent_incidents', '—'))} incidents"})
    return rows[:5]
