"""Phase 6: evidence-grounded Intelligence Copilot orchestration.

The LLM, when available, is only asked to explain a compact context selected
by deterministic routing. Numeric evidence and navigation actions are owned by
the application, not generated by the model.
"""
from __future__ import annotations

import json
import logging
import os
import re
from datetime import datetime, time
from typing import Any

import requests
from sqlalchemy import func
from sqlalchemy.orm import Session

from .models import Incident, Ward
from .intelligence_brief import generate_intelligence_brief
from .prediction import predict_risk
from .trend_analysis import analyze_trends
from .alert_engine import generate_alerts
from .analytics import detect_hotspots
from .network_analysis import build_network

logger = logging.getLogger("copilot")

INTENTS = ("SUMMARY", "RISK", "TREND", "ALERT", "HOTSPOT", "NETWORK", "OFFENDER", "INCIDENT", "COMPARE", "FOLLOW_UP", "GENERAL_ANALYTICS", "UNAVAILABLE_DATA", "OUT_OF_SCOPE")
SUPPORTED_ACTIONS = {"view_brief", "view_district", "view_ward", "view_trend", "view_risk", "view_alerts", "view_hotspots", "view_network"}

# Topics that sound like dashboard questions but reference data this
# application does not track at all (no judicial-outcome fields exist on any
# model). Caught before general routing so the answer is an explicit "not
# available" instead of a deflection into unrelated evidence.
UNAVAILABLE_DATA_TOPICS = (
    "conviction rate", "conviction", "clearance rate", "solve rate", "solved rate",
    "court verdict", "sentencing", "prosecution rate", "acquittal",
)

# Explicit hotspot nouns (deliberately excluding the very generic "where",
# which stays in the later, lower-priority HOTSPOT check) and the forecast
# verbs that let a genuine prediction question outrank them. See route_intent.
_HOTSPOT_NOUNS = ("hotspot", "hot spot", "cluster", "ಹಾಟ್‌ಸ್ಪಾಟ್", "ಹಾಟ್ ಸ್ಪಾಟ್", "हॉटस्पॉट")
_FORECAST_VERBS = ("predict", "forecast", "ಮುನ್ಸೂಚನೆ", "पूर्वानुमान")


def _localized_level(value: Any, lang: str) -> str:
    """Translate dashboard status words that otherwise leak into AI output."""
    value = str(value or "").lower()
    labels = {
        "kn": {"critical": "ಗಂಭೀರ", "high": "ಹೆಚ್ಚಿನ", "medium": "ಮಧ್ಯಮ", "low": "ಕಡಿಮೆ", "rising": "ಹೆಚ್ಚುತ್ತಿದೆ", "falling": "ಕಡಿಮೆಯಾಗುತ್ತಿದೆ", "stable": "ಸ್ಥಿರ"},
        "hi": {"critical": "गंभीर", "high": "उच्च", "medium": "मध्यम", "low": "निम्न", "rising": "बढ़ता हुआ", "falling": "घटता हुआ", "stable": "स्थिर"},
    }
    return labels.get(lang, {}).get(value, value.upper())


def route_intent(message: str) -> str:
    """
    Ordered, mutually-exclusive keyword routing. Order matters: earlier
    branches win. Two failure modes drove this ordering —
      1. "attention"/"priority" used to sit in the RISK keyword list, so any
         analytical question phrased as "what should an investigator pay
         attention to" was misrouted into forecast-only evidence and got the
         RISK branch's insufficient-data text, however good the historical
         data actually was for a *descriptive* answer.
      2. A bare "why"/"next" catch-all used to run BEFORE the domain-specific
         checks and defaulted to RISK, so e.g. "...anomalies... explain why
         each one is important" (a TREND question) was misrouted to RISK too.
    Domain-specific checks now all run before that catch-all, RISK no longer
    fires on generic analytical language, and the catch-all's result is
    FOLLOW_UP (general-analytics evidence), never RISK — RISK is reserved for
    genuine forecast/prediction language.
    """
    q = message.lower()
    if any(x in q for x in ("cricket", "football", "weather", "stock price", "recipe", "movie review")): return "OUT_OF_SCOPE"
    if any(x in q for x in UNAVAILABLE_DATA_TOPICS): return "UNAVAILABLE_DATA"
    # A hotspot noun outranks the generic "compare"/"risk" keywords below:
    # - "Compare the top 5 hotspots" matched COMPARE first, which only knows
    #   how to compare two named WARDS by text-matching; finding none, it
    #   dead-ended with "I could not reliably identify two wards to compare"
    #   instead of ranking hotspots (which the HOTSPOT evidence already
    #   contains, pre-sorted by risk, and the LLM prompt already knows to
    #   render a comparison of several ranked items as a table).
    # - "which hotspot has the highest RISK score" / "highest-RISK hotspots"
    #   are questions about DBSCAN cluster risk scores (descriptive, from
    #   detect_hotspots), not the ward-level predictive forecast; they used
    #   to match the RISK branch below and come back with forecast evidence
    #   and no hotspot data at all.
    # Explicit forecast verbs still win, so "predict future hotspots" still
    # routes to the predictive model, and a ward-to-ward comparison with no
    # hotspot noun ("compare Ward A and Ward B") is untouched.
    if any(x in q for x in _HOTSPOT_NOUNS) and not any(x in q for x in _FORECAST_VERBS): return "HOTSPOT"
    if any(x in q for x in ("compare", "versus", " vs ", "difference between")): return "COMPARE"
    if "which ward" in q and any(x in q for x in ("attention", "priority", "focus")): return "SUMMARY"
    if any(x in q for x in ("risk", "predict", "forecast", "future", "high risk", "ಅಪಾಯ", "ಮುನ್ಸೂಚನೆ", "जोखिम", "पूर्वानुमान")): return "RISK"
    if any(x in q for x in ("trend", "changed", "change", "rising", "increasing", "baseline", "anomal", "ಪ್ರವೃತ್ತ", "ಬದಲಾವಣೆ", "ट्रेंड", "परिवर्तन", "बढ़")): return "TREND"
    if any(x in q for x in ("alert", "warning", "ಎಚ್ಚರ", "अलर्ट", "चेतावनी")): return "ALERT"
    if any(x in q for x in ("hotspot", "cluster", "where", "ಹಾಟ್‌ಸ್ಪಾಟ್", "ಹಾಟ್ ಸ್ಪಾಟ್", "हॉटस्पॉट")): return "HOTSPOT"
    if any(x in q for x in ("network", "connected", "connector", "community", "linked", "ಜಾಲ", "नेटवर्क", "जुड़")): return "NETWORK"
    if any(x in q for x in ("offender", "accused", "repeat", "ಅಪರಾಧಿ", "ಆರೋಪಿ", "अपराधी", "आरोपी")): return "OFFENDER"
    if any(x in q for x in ("summar", "important", "intelligence picture", "what's here", "what is here")): return "SUMMARY"
    # "incident(s)" alone is too generic to mean "show raw recent records" —
    # it appears in almost any crime question. Only route to a raw incident
    # dump for language that specifically asks for recent/latest activity.
    if any(x in q for x in ("happened", "recent incident", "latest incident", "recent activity", "ಘಟನೆ", "घटना")): return "INCIDENT"
    if any(x in q for x in ("why", "what should i inspect", "next", "follow-up")) and "alert" not in q and "risk" not in q:
        return "FOLLOW_UP"
    return "GENERAL_ANALYTICS"


def _dates(context: dict) -> tuple[datetime | None, datetime | None]:
    def parse(value, end_of_day=False):
        try:
            parsed = datetime.fromisoformat(value) if value else None
            if parsed and end_of_day and "T" not in value and " " not in value:
                return datetime.combine(parsed.date(), time.max)
            return parsed
        except (TypeError, ValueError): return None
    return parse(context.get("date_from")), parse(context.get("date_to"), end_of_day=True)


def _extract_district_from_text(db: Session, message: str) -> str | None:
    """
    Best-effort scope detection from free text — e.g. "Analyze Kalaburagi
    district" should be Kalaburagi-scoped even when the dashboard's district
    filter isn't set, matching against real district names rather than
    guessing or inventing one.
    """
    q = message.lower()
    for (name,) in db.query(Ward.district).distinct().all():
        if name and name.lower() in q:
            return name
    return None


def _scope(db: Session, message: str, context: dict) -> tuple[str | None, int | None, str | None]:
    district = context.get("district") or context.get("selectedDistrict")
    ward_id = context.get("ward_id")
    if ward_id is None and isinstance(context.get("selectedWard"), dict): ward_id = context["selectedWard"].get("id")
    crime = context.get("crime_type") or context.get("selectedCrimeType")
    if not district and ward_id is None:
        district = _extract_district_from_text(db, message)
    return district or None, int(ward_id) if ward_id is not None else None, crime or None


def _action(label: str, action: str, **extra) -> dict:
    return {"label": label, "action": action, **extra} if action in SUPPORTED_ACTIONS else {}


def _brief_context(db, district, ward_id, crime, date_from, date_to, horizon, granularity):
    return generate_intelligence_brief(db, district=district, ward_id=ward_id, crime_type=crime,
                                       date_from=date_from, date_to=date_to, horizon_days=horizon,
                                       granularity=granularity)


def _dataset_overview(db: Session, crime_type: str | None = None, date_from=None, date_to=None, top_n: int = 8) -> dict:
    """
    Dataset-wide descriptive snapshot — no ML, no forecasting — for questions
    that ask about the current data as a whole rather than one district/ward
    (e.g. "which districts have the most incidents", "what crime types are
    most common"). generate_intelligence_brief() cannot answer these: it is
    built around a single district/ward drilldown and returns
    "selection_required" without one. This is a straightforward COUNT/GROUP
    BY over the same Incident table every other module already queries.
    """
    q = db.query(Incident)
    if crime_type: q = q.filter(Incident.crime_type == crime_type)
    if date_from: q = q.filter(Incident.timestamp >= date_from)
    if date_to: q = q.filter(Incident.timestamp <= date_to)
    total = q.count()
    if total == 0:
        return {"status": "no_data", "total_incidents": 0}
    by_district = (q.with_entities(Incident.district, func.count(Incident.id))
                    .group_by(Incident.district).order_by(func.count(Incident.id).desc()).limit(top_n).all())
    by_crime_type = (q.with_entities(Incident.crime_type, func.count(Incident.id))
                       .group_by(Incident.crime_type).order_by(func.count(Incident.id).desc()).limit(top_n).all())
    date_bounds = q.with_entities(func.min(Incident.timestamp), func.max(Incident.timestamp)).first()
    return {
        "status": "ok",
        "total_incidents": total,
        "districts_by_incident_count": [{"district": d, "count": n} for d, n in by_district],
        "crime_types_by_count": [{"crime_type": c, "count": n} for c, n in by_crime_type],
        "date_range": {
            "from": date_bounds[0].isoformat() if date_bounds and date_bounds[0] else None,
            "to": date_bounds[1].isoformat() if date_bounds and date_bounds[1] else None,
        },
    }


def _summarize_risk(risk: dict, top_n: int = 15) -> dict:
    """
    predict_risk() returns one row per ward in scope — for a dataset-wide or
    district-wide (no single ward) request that can be 100+ rows, each
    carrying a verbose SHAP explanation. _compact()'s generic size-based
    truncation has no notion of "predictions" and would silently drop the
    entire list once the serialized evidence crosses its size limit, making
    a genuinely available forecast look like "no data" downstream. Trim to
    the top-N highest-risk wards with only the essential fields (dropping
    per-ward SHAP factor breakdowns, which the dashboard's own risk view
    already renders) so the real forecast signal survives compaction.
    """
    preds = risk.get("predictions") or []
    if len(preds) <= top_n:
        return risk
    valid = sorted((p for p in preds if not p.get("insufficient_data")), key=lambda p: p.get("risk_score") or 0, reverse=True)
    kept_source = valid if valid else preds
    kept = [
        {k: p.get(k) for k in ("ward_id", "ward_name", "district", "prediction_horizon_days",
                                "insufficient_data", "risk_score", "risk_level", "predicted_incidents",
                                "confidence", "trend")}
        for p in kept_source[:top_n]
    ]
    return {**risk, "predictions": kept,
            "predictions_summary": {"total_wards": len(preds), "wards_with_valid_forecast": len(valid), "shown": len(kept)}}


def _summarize_hotspots(hotspots: dict, top_n: int = 10) -> dict:
    """
    detect_hotspots() returns every clustered incident coordinate: a global
    scope serializes to ~590KB (a 2400-entry `points` list, plus a per-cluster
    `points` list inside each of ~91 clusters). That is ~65x _compact()'s size
    limit, and _compact()'s generic truncation has no notion of "n_clusters",
    so it discarded every count and left only `params` — which is why the
    Copilot reported "0 clusters from 0 incidents" while the Hotspots
    dashboard, reading the same detect_hotspots() output straight from
    /api/hotspots, correctly showed 91 clusters from 2400 incidents.

    Keep the headline counts and the top-N clusters by risk score, dropping
    only the raw coordinate lists (the map renders those from /api/hotspots
    itself; they carry no analytical meaning for a text answer).
    """
    clusters = hotspots.get("clusters") or []
    ranked = sorted(clusters, key=lambda c: c.get("risk_score") or 0, reverse=True)
    return {
        "params": hotspots.get("params"),
        "auto_tuned": hotspots.get("auto_tuned"),
        "n_incidents": hotspots.get("n_incidents", 0),
        "n_clusters": hotspots.get("n_clusters", 0),
        "n_noise": hotspots.get("n_noise", 0),
        "severity_breakdown": {
            level: sum(1 for c in clusters if c.get("severity_level") == level)
            for level in ("High", "Medium", "Low")
        },
        "districts_by_hotspot_count": [
            {"district": d, "hotspots": n, "max_risk_score": m}
            for d, n, m in sorted(
                ((d, sum(1 for c in clusters if c.get("district") == d),
                  max((c.get("risk_score") or 0) for c in clusters if c.get("district") == d))
                 for d in {c.get("district") for c in clusters if c.get("district")}),
                key=lambda row: (row[2], row[1]), reverse=True)[:top_n]
        ],
        "top_clusters": [
            {k: c.get(k) for k in ("cluster_id", "district", "ward_id", "risk_score", "severity_level",
                                    "incident_count", "dominant_crime_type", "avg_severity", "radius_m", "centroid")}
            for c in ranked[:top_n]
        ],
        "clusters_shown": min(len(ranked), top_n),
    }


def _compact(data: Any, limit: int = 9000):
    if not data:
        return None
    serialized = json.dumps(data, default=str, allow_nan=False)
    if len(serialized) <= limit:
        return json.loads(serialized)
    if isinstance(data, dict):
        compact = {k: data[k] for k in ("status", "summary", "params", "scope", "priority", "headline", "key_development", "predictive_risk", "alerts", "hotspots", "network", "why_it_matters", "analytical_followups", "predictions", "predictions_summary", "model_performance", "n_incidents", "n_clusters", "n_noise", "severity_breakdown", "districts_by_hotspot_count", "top_clusters", "clusters_shown") if k in data}
        return json.loads(json.dumps(compact, default=str, allow_nan=False))
    return {"truncated": True, "summary": f"{len(data)} records available; only a compact analytical summary was supplied."}


def build_evidence_context(db: Session, message: str, context: dict) -> dict:
    intent = route_intent(message)
    district, ward_id, crime = _scope(db, message, context)
    date_from, date_to = _dates(context)
    horizon = int(context.get("prediction_horizon") or context.get("horizonDays") or 14)
    granularity = context.get("granularity") or context.get("trendGranularity") or "weekly"
    base = {"intent": intent, "scope": {"district": district, "ward_id": ward_id, "crime_type": crime}, "sources": []}

    if intent == "UNAVAILABLE_DATA":
        base.update({"sources": []})
        return base
    if intent in ("SUMMARY", "FOLLOW_UP", "GENERAL_ANALYTICS"):
        if district or ward_id is not None:
            brief = _brief_context(db, district, ward_id, crime, date_from, date_to, horizon, granularity)
            base.update({"brief": _compact(brief), "sources": ["Intelligence Brief"]})
        else:
            base.update({"overview": _dataset_overview(db, crime_type=crime, date_from=date_from, date_to=date_to), "sources": ["Dataset Overview"]})
        return base
    if intent == "OUT_OF_SCOPE":
        base.update({"sources": []})
        return base
    if intent == "RISK":
        risk = predict_risk(db, district=district, ward_id=ward_id, crime_type=crime, horizon_days=horizon, as_of=date_to)
        base.update({"risk": _compact(_summarize_risk(risk)), "sources": ["Predictive Risk"]})
        # Forecast evidence alone can't answer "what's happening now" — attach
        # the same current-data context SUMMARY uses, so a RISK-intent question
        # can still be answered descriptively when the forecast is unreliable.
        if district or ward_id is not None:
            base["brief"] = _compact(_brief_context(db, district, ward_id, crime, date_from, date_to, horizon, granularity))
            base["sources"].append("Intelligence Brief")
        else:
            base["overview"] = _dataset_overview(db, crime_type=crime, date_from=date_from, date_to=date_to)
            base["sources"].append("Dataset Overview")
        return base
    if intent == "TREND":
        trend = analyze_trends(db, district=district, ward_id=ward_id, crime_type=crime, date_from=date_from, date_to=date_to, granularity=granularity)
        base.update({"trend": _compact(trend), "sources": ["Trend Analytics"]})
        return base
    if intent == "ALERT":
        alerts = generate_alerts(db, district=district, ward_id=ward_id, crime_type=crime, date_from=date_from, date_to=date_to, granularity=granularity)
        base.update({"alerts": _compact(alerts), "sources": ["Intelligence Alerts"]})
        return base
    if intent == "HOTSPOT":
        hotspots = detect_hotspots(db, district=district, crime_type=crime, date_from=date_from, date_to=date_to)
        logger.info(
            "copilot hotspot query: district=%s crime_type=%s date_from=%s date_to=%s -> n_incidents=%s n_clusters=%s",
            district, crime, date_from, date_to, hotspots.get("n_incidents"), hotspots.get("n_clusters"),
        )
        base.update({"hotspots": _compact(_summarize_hotspots(hotspots)), "sources": ["Hotspot Analytics"]})
        return base
    if intent in ("NETWORK", "OFFENDER"):
        network = build_network(db, ward_id=ward_id, district=district, crime_type=crime, date_from=date_from, date_to=date_to)
        if intent == "OFFENDER":
            network = {"summary": network.get("summary"), "nodes": [n for n in network.get("nodes", []) if n.get("incident_count", 0) > 1][:8]}
        base.update({"network": _compact(network), "sources": ["Network Analytics", "Repeat Offender Analytics"]})
        return base
    if intent == "INCIDENT":
        # Pre-existing bug: .limit() must come after .filter() — SQLAlchemy
        # rejects filtering a query that already has LIMIT/OFFSET applied,
        # so any district/ward/crime-scoped "recent incidents" question
        # (e.g. from AI Mitra with a district selected) raised
        # InvalidRequestError and surfaced as a raw 500 from /api/copilot.
        q = db.query(Incident)
        if district: q = q.filter(Incident.district == district)
        if ward_id is not None: q = q.filter(Incident.ward_id == ward_id)
        if crime: q = q.filter(Incident.crime_type == crime)
        q = q.order_by(Incident.timestamp.desc()).limit(5)
        incidents = [{"id": i.id, "timestamp": i.timestamp.isoformat(), "crime_type": i.crime_type, "severity": i.severity, "district": i.district, "ward_id": i.ward_id} for i in q.all()]
        base.update({"incidents": incidents, "sources": ["Incident Records"]})
        return base
    return base


def _find_compare_wards(db: Session, message: str, district: str | None) -> list[Ward]:
    wards = db.query(Ward).filter(Ward.district == district).all() if district else db.query(Ward).all()
    q = message.lower()
    matches = [w for w in wards if w.name.lower() in q]
    return matches[:2] if len(matches) >= 2 else []


def _overview_text_en(ov: dict) -> str:
    if ov.get("status") != "ok":
        return "No incident data matches the current filters."
    d_txt = ", ".join(f"{d['district']} ({d['count']})" for d in ov.get("districts_by_incident_count", [])[:3])
    c_txt = ", ".join(f"{c['crime_type']} ({c['count']})" for c in ov.get("crime_types_by_count", [])[:3])
    return f"Across {ov['total_incidents']} recorded incidents, the highest-incident districts are {d_txt}. The most common crime types are {c_txt}."


def _overview_text_kn(ov: dict) -> str:
    if ov.get("status") != "ok":
        return "ಪ್ರಸ್ತುತ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದುವ ಘಟನೆಗಳಿಲ್ಲ."
    d_txt = ", ".join(f"{d['district']} ({d['count']})" for d in ov.get("districts_by_incident_count", [])[:3])
    c_txt = ", ".join(f"{c['crime_type']} ({c['count']})" for c in ov.get("crime_types_by_count", [])[:3])
    return f"ಒಟ್ಟು {ov['total_incidents']} ದಾಖಲಾದ ಘಟನೆಗಳಲ್ಲಿ, ಅತಿ ಹೆಚ್ಚು ಘಟನೆಗಳಿರುವ ಜಿಲ್ಲೆಗಳು: {d_txt}. ಅತಿ ಸಾಮಾನ್ಯ ಅಪರಾಧ ಪ್ರಕಾರಗಳು: {c_txt}."


def _overview_text_hi(ov: dict) -> str:
    if ov.get("status") != "ok":
        return "मौजूदा फ़िल्टर से मेल खाने वाली कोई घटना नहीं है।"
    d_txt = ", ".join(f"{d['district']} ({d['count']})" for d in ov.get("districts_by_incident_count", [])[:3])
    c_txt = ", ".join(f"{c['crime_type']} ({c['count']})" for c in ov.get("crime_types_by_count", [])[:3])
    return f"कुल {ov['total_incidents']} दर्ज घटनाओं में सबसे अधिक घटनाओं वाले जिले हैं: {d_txt}। सबसे सामान्य अपराध प्रकार हैं: {c_txt}।"


def _fallback(message: str, evidence: dict, db: Session, lang: str = "en") -> tuple[str, list[dict]]:
    intent, scope = evidence["intent"], evidence["scope"]
    name = scope.get("district") or "the selected scope"
    actions = []

    if lang == "kn":
        if intent == "UNAVAILABLE_DATA":
            return "ಈ ಮಾಹಿತಿ ಈ ಅಪ್ಲಿಕೇಶನ್‌ನ ಡೇಟಾಸೆಟ್‌ನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ (ಉದಾ: ಶಿಕ್ಷೆ ಪ್ರಮಾಣ ಅಥವಾ ನ್ಯಾಯಾಲಯದ ಫಲಿತಾಂಶಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಲಾಗುವುದಿಲ್ಲ).", []
        if intent in ("SUMMARY", "FOLLOW_UP", "GENERAL_ANALYTICS"):
            b = evidence.get("brief")
            if b is not None:
                if b.get("status") == "selection_required":
                    return "ವಿಶ್ಲೇಷಣೆ ನಡೆಸಲು ದಯವಿಟ್ಟು ಮೊದಲಿಗೆ ಜಿಲ್ಲೆ ಅಥವಾ ವಾರ್ಡ್ ಆಯ್ಕೆ ಮಾಡಿ.", []
                p = b.get("priority", {})
                answer = f"{b.get('scope', {}).get('name', name)} ಜಿಲ್ಲೆಗೆ {p.get('score', '—')}/100 ಪ್ರಮುಖತೆಯ ಅಂಕವಿದೆ. ಲಭ್ಯವಿರುವ ವಿಶ್ಲೇಷಣೆಯ ಆಧಾರದಲ್ಲಿ ಆದ್ಯತೆಯ ಕ್ರಮಗಳನ್ನು ಪರಿಶೀಲಿಸಿ."
                actions = b.get("analytical_followups", [])
            else:
                answer = _overview_text_kn(evidence.get("overview") or {})
        elif intent == "RISK":
            ps = (evidence.get("risk") or {}).get("predictions", [])
            p = ps[0] if ps else None
            valid = [x for x in ps if not x.get("insufficient_data")]
            if p and not p.get("insufficient_data"):
                answer = f"ಮುಂದಿನ {p['prediction_horizon_days']} ದಿನಗಳಲ್ಲಿ ಮಾದರಿಯು {p['risk_score']}/100 {_localized_level(p['risk_level'], lang)} ಅಪಾಯವನ್ನು ಅಂದಾಜಿಸಿದೆ."
            elif valid:
                best = max(valid, key=lambda x: x["risk_score"] or 0)
                answer = f"ಈ ನಿರ್ದಿಷ್ಟ ಆಯ್ಕೆಗೆ ವಿಶ್ವಾಸಾರ್ಹ ಮುನ್ಸೂಚನೆ ಇಲ್ಲ, ಆದರೆ {best['ward_name']} ಗೆ {best['risk_score']}/100 {_localized_level(best['risk_level'], lang)} ಅಪಾಯದ ಅಂದಾಜು ಲಭ್ಯವಿದೆ."
            else:
                answer = "ಈ ವ್ಯಾಪ್ತಿಗೆ ವಿಶ್ವಾಸಾರ್ಹ ಮುನ್ಸೂಚನೆ ನೀಡಲು ಸಾಕಷ್ಟು ಐತಿಹಾಸಿಕ ಮಾಹಿತಿ ಇಲ್ಲ, ಆದರೆ ಪ್ರಸ್ತುತ ಘಟನೆ ಮಾಹಿತಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಬಲ್ಲೆ."
            actions = [_action("ಅಪಾಯ ವೀಕ್ಷಿಸಿ", "view_risk")]
        elif intent == "TREND":
            t = evidence.get("trend") or {}
            if t.get("status") == "insufficient_data":
                answer = "ಈ ವ್ಯಾಪ್ತಿಗೆ ಪ್ರವೃತ್ತಿ ವ್ಯತ್ಯಾಸವನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಸಾಕಷ್ಟು ಐತಿಹಾಸಿಕ ಮಾಹಿತಿ ಇಲ್ಲ."
            else:
                candidates = t.get("anomalies") or t.get("top_emerging_trends") or []
                top = max(candidates, key=lambda x: abs(x.get("percentage_change", x.get("change_percent", 0)) or 0), default=None)
                answer = "ಈ ಅವಧಿಯಲ್ಲಿ ಯಾವುದೇ ಗಮನಾರ್ಹ ಅಪರಾಧ ವ್ಯತ್ಯಾಸ ಕಂಡುಬಂದಿಲ್ಲ." if not top else f"{top.get('crime_type') or 'ಅಪರಾಧ'} ಪ್ರವೃತ್ತಿಯು {top.get('percentage_change', top.get('change_percent', '—'))}% ಬದಲಾವಣೆಯನ್ನು ತೋರಿಸುತ್ತಿದೆ."
            actions = [_action("ಟ್ರೆಂಡ್ ವೀಕ್ಷಿಸಿ", "view_trend")]
        elif intent == "ALERT":
            a = evidence.get("alerts") or {}; s = a.get("summary", {})
            answer = f"ಈ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ ಒಟ್ಟು {s.get('total', 0)} ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳಿವೆ, ಇದರಲ್ಲಿ {s.get('critical', 0)} ಗಂಭೀರ ಮತ್ತು {s.get('high', 0)} ಹೆಚ್ಚಿನ ತೀವ್ರತೆಯ ಎಚ್ಚರಿಕೆಗಳಿವೆ."
            actions = [_action("ಎಚ್ಚರಿಕೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ", "view_alerts")]
        elif intent == "HOTSPOT":
            h = evidence.get("hotspots") or {}
            answer = f"{h.get('n_incidents', 0)} ಘಟನೆಗಳಿಂದ ಒಟ್ಟು {h.get('n_clusters', 0)} ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ಗುರುತಿಸಲಾಗಿದೆ."
            if h.get("top_clusters"):
                t = h["top_clusters"][0]
                answer += f" ಅತಿ ಹೆಚ್ಚು ಅಪಾಯದ ಹಾಟ್‌ಸ್ಪಾಟ್ {t.get('district')} ನಲ್ಲಿದೆ ({t.get('risk_score')}/100, {t.get('incident_count')} ಘಟನೆಗಳು)."
            actions = [_action("ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ವೀಕ್ಷಿಸಿ", "view_hotspots")]
        elif intent in ("NETWORK", "OFFENDER"):
            n = evidence.get("network") or {}; s = n.get("summary") or {}; answer = f"ಅಪರಾಧ ಜಾಲವು {s.get('n_communities', 0)} ಗುಂಪುಗಳಲ್ಲಿ {s.get('n_nodes', 0)} ಅಪರಾಧಿಗಳನ್ನು ಒಳಗೊಂಡಿದೆ."; actions = [_action("ಜಾಲ ತೆರೆಯಿರಿ", "view_network")]
        elif intent == "INCIDENT":
            rows = evidence.get("incidents") or []; answer = "ಇತ್ತೀಚಿನ ಘಟನೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ." if not rows else "ಇತ್ತೀಚಿನ ಅಪರಾಧಗಳು: " + "; ".join(f"{r['crime_type']} ({r['severity']}/10)" for r in rows[:3])
        elif intent == "OUT_OF_SCOPE":
            answer = "ನಾನು ಅಪರಾಧ ವಿಶ್ಲೇಷಣೆ, ಟ್ರೆಂಡ್‌ಗಳು, ಎಚ್ಚರಿಕೆಗಳು, ಅಪಾಯಗಳು ಮತ್ತು ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳ ಬಗ್ಗೆ ಮಾಹಿತಿ ನೀಡಬಲ್ಲೆ."
        else:
            answer = "ಅಪರಾಧ ವಿಶ್ಲೇಷಣೆ, ಟ್ರೆಂಡ್‌ಗಳು, ಎಚ್ಚರಿಕೆಗಳು, ಅಪಾಯಗಳು, ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ಮತ್ತು ಅಪರಾಧಿ ಜಾಲದ ಬಗ್ಗೆ ಕೇಳಿ."
        return answer, [a for a in actions if a]

    elif lang == "hi":
        if intent == "UNAVAILABLE_DATA":
            return "यह जानकारी इस एप्लिकेशन के डेटासेट में उपलब्ध नहीं है (जैसे सजा दर या अदालती फैसले ट्रैक नहीं किए जाते हैं)।", []
        if intent in ("SUMMARY", "FOLLOW_UP", "GENERAL_ANALYTICS"):
            b = evidence.get("brief")
            if b is not None:
                if b.get("status") == "selection_required":
                    return "विश्लेषण के लिए कृपया पहले एक जिला या वार्ड चुनें।", []
                p = b.get("priority", {})
                answer = f"{b.get('scope', {}).get('name', name)} का प्राथमिकता स्कोर {p.get('score', '—')}/100 है। उपलब्ध विश्लेषण के आधार पर प्राथमिक कार्रवाई की समीक्षा करें।"
                actions = b.get("analytical_followups", [])
            else:
                answer = _overview_text_hi(evidence.get("overview") or {})
        elif intent == "RISK":
            ps = (evidence.get("risk") or {}).get("predictions", [])
            p = ps[0] if ps else None
            valid = [x for x in ps if not x.get("insufficient_data")]
            if p and not p.get("insufficient_data"):
                answer = f"मॉडल अगले {p['prediction_horizon_days']} दिनों में {p['risk_score']}/100 {_localized_level(p['risk_level'], lang)} जोखिम का अनुमान लगाता है।"
            elif valid:
                best = max(valid, key=lambda x: x["risk_score"] or 0)
                answer = f"इस सटीक चयन के लिए विश्वसनीय पूर्वानुमान उपलब्ध नहीं है, लेकिन {best['ward_name']} के लिए {best['risk_score']}/100 {_localized_level(best['risk_level'], lang)} जोखिम का अनुमान उपलब्ध है।"
            else:
                answer = "इस क्षेत्र के लिए विश्वसनीय पूर्वानुमान हेतु पर्याप्त ऐतिहासिक डेटा नहीं है, लेकिन मैं मौजूदा घटना डेटा का विश्लेषण कर सकता हूँ।"
            actions = [_action("जोखिम देखें", "view_risk")]
        elif intent == "TREND":
            t = evidence.get("trend") or {}
            if t.get("status") == "insufficient_data":
                answer = "इस क्षेत्र के लिए प्रवृत्ति विसंगति का पता लगाने हेतु पर्याप्त ऐतिहासिक डेटा नहीं है।"
            else:
                candidates = t.get("anomalies") or t.get("top_emerging_trends") or []
                top = max(candidates, key=lambda x: abs(x.get("percentage_change", x.get("change_percent", 0)) or 0), default=None)
                answer = "इस क्षेत्र के लिए कोई महत्वपूर्ण प्रवृत्ति विसंगति नहीं पाई गई।" if not top else f"{top.get('crime_type') or 'अपराध'} में {top.get('percentage_change', top.get('change_percent', '—'))}% परिवर्तन देखा गया है।"
            actions = [_action("ट्रेंड देखें", "view_trend")]
        elif intent == "ALERT":
            a = evidence.get("alerts") or {}; s = a.get("summary", {})
            answer = f"इस क्षेत्र में कुल {s.get('total', 0)} सक्रिय खुफिया अलर्ट हैं, जिनमें {s.get('critical', 0)} गंभीर और {s.get('high', 0)} उच्च-तीव्रता वाले अलर्ट शामिल हैं।"
            actions = [_action("अलर्ट देखें", "view_alerts")]
        elif intent == "HOTSPOT":
            h = evidence.get("hotspots") or {}
            answer = f"{h.get('n_incidents', 0)} घटनाओं से {h.get('n_clusters', 0)} हॉटस्पॉट क्लस्टर पाए गए।"
            if h.get("top_clusters"):
                t = h["top_clusters"][0]
                answer += f" सबसे अधिक जोखिम वाला हॉटस्पॉट {t.get('district')} में है ({t.get('risk_score')}/100, {t.get('incident_count')} घटनाएँ)।"
            actions = [_action("हॉटस्पॉट देखें", "view_hotspots")]
        elif intent in ("NETWORK", "OFFENDER"):
            n = evidence.get("network") or {}; s = n.get("summary") or {}; answer = f"नेटवर्क में {s.get('n_communities', 0)} समूहों में {s.get('n_nodes', 0)} जुड़े अपराधी शामिल हैं।"; actions = [_action("नेटवर्क खोलें", "view_network")]
        elif intent == "INCIDENT":
            rows = evidence.get("incidents") or []; answer = "कोई हालिया घटना नहीं मिली।" if not rows else "हाल की घटनाएं: " + "; ".join(f"{r['crime_type']} ({r['severity']}/10)" for r in rows[:3])
        elif intent == "OUT_OF_SCOPE":
            answer = "मैं अपराध विश्लेषण, ट्रेंड्स, अलर्ट्स, जोखिम और हॉटस्पॉट के बारे में जानकारी दे सकता हूँ।"
        else:
            answer = "अपराध विश्लेषण, ट्रेंड्स, अलर्ट्स, जोखिम, हॉटस्पॉट और आपराधिक नेटवर्क के बारे में पूछें।"
        return answer, [a for a in actions if a]

    else:
        if intent == "UNAVAILABLE_DATA":
            return "That information is not available in this application's dataset (for example, conviction rates and court outcomes are not tracked).", []
        if intent in ("SUMMARY", "FOLLOW_UP", "GENERAL_ANALYTICS"):
            b = evidence.get("brief")
            if b is not None:
                if b.get("status") == "selection_required":
                    return "Select a district or ward first so I can ground the summary in the available intelligence analytics.", []
                p = b.get("priority", {})
                answer = f"{b.get('scope', {}).get('name', name)} has {p.get('level', 'available')} priority ({p.get('score', '—')}/100). {b.get('headline', 'No consolidated intelligence brief is available.') }"
                if b.get("why_it_matters"): answer += " " + " ".join(b["why_it_matters"][:2])
                actions = b.get("analytical_followups", [])
            else:
                answer = _overview_text_en(evidence.get("overview") or {})
        elif intent == "RISK":
            ps = (evidence.get("risk") or {}).get("predictions", [])
            p = ps[0] if ps else None
            valid = [x for x in ps if not x.get("insufficient_data")]
            if p and not p.get("insufficient_data"):
                answer = f"The model estimates {p['risk_score']}/100 {p['risk_level'].upper()} risk over the next {p['prediction_horizon_days']} days."
            elif valid:
                best = max(valid, key=lambda x: x["risk_score"] or 0)
                answer = (f"A reliable forecast isn't available for this exact selection, but {len(valid)} of {len(ps)} wards in scope do have one — "
                          f"the highest is {best['ward_name']} at {best['risk_score']}/100 {best['risk_level'].upper()} risk over the next {best['prediction_horizon_days']} days.")
            else:
                answer = "I can analyze the current incident data, but the available historical time series is insufficient for a reliable future forecast in this scope."
            actions = [_action("View Risk", "view_risk")]
        elif intent == "TREND":
            t = evidence.get("trend") or {}
            if t.get("status") == "insufficient_data":
                answer = "There isn't enough historical time-series data yet to reliably detect trend anomalies for this scope."
            else:
                candidates = t.get("anomalies") or t.get("top_emerging_trends") or []
                top = max(candidates, key=lambda x: abs(x.get("percentage_change", x.get("change_percent", 0)) or 0), default=None)
                answer = "No significant trend anomaly was detected for this scope." if not top else f"{top.get('crime_type') or 'Crime'} is showing a {top.get('direction', 'rising')} signal with a {top.get('percentage_change', top.get('change_percent', '—'))}% change."
            actions = [_action("View Trend", "view_trend")]
        elif intent == "ALERT":
            a = evidence.get("alerts") or {}; s = a.get("summary", {})
            answer = f"There are {s.get('total', 0)} active intelligence alerts in this scope, including {s.get('critical', 0)} critical and {s.get('high', 0)} high-severity alerts."
            actions = [_action("View Alerts", "view_alerts")]
        elif intent == "HOTSPOT":
            h = evidence.get("hotspots") or {}
            answer = f"{h.get('n_clusters', 0)} active hotspot clusters were detected from {h.get('n_incidents', 0)} incidents."
            sev = h.get("severity_breakdown") or {}
            if sev.get("High") or sev.get("Medium") or sev.get("Low"):
                answer += f" Severity split: {sev.get('High', 0)} high, {sev.get('Medium', 0)} medium, {sev.get('Low', 0)} low."
            if h.get("top_clusters"):
                t = h["top_clusters"][0]
                answer += f" The highest-risk hotspot is in {t.get('district')} at {t.get('risk_score')}/100 ({t.get('incident_count')} incidents, mainly {t.get('dominant_crime_type')})."
            actions = [_action("View Hotspots", "view_hotspots")]
        elif intent in ("NETWORK", "OFFENDER"):
            n = evidence.get("network") or {}; s = n.get("summary") or {}; answer = f"The network contains {s.get('n_nodes', 0)} linked offenders across {s.get('n_communities', 0)} communities."; actions = [_action("Open Network", "view_network")]
        elif intent == "INCIDENT":
            rows = evidence.get("incidents") or []; answer = "No recent incidents were found." if not rows else "Recent records: " + "; ".join(f"{r['crime_type']} ({r['severity']}/10)" for r in rows[:3])
        elif intent == "COMPARE":
            rows = evidence.get("comparison") or []
            ranked = sorted(rows, key=lambda x: (x.get("brief", {}).get("priority", {}).get("score") or -1), reverse=True)
            if not ranked:
                answer = "I could not reliably identify two wards to compare."
            else:
                answer = "Comparison: " + "; ".join(f"{x['ward']} has {x.get('brief', {}).get('priority', {}).get('level', 'unavailable')} priority ({x.get('brief', {}).get('priority', {}).get('score', '—')}/100)" for x in ranked)
                top = ranked[0]; scope = evidence.get("scope", {})
                actions = [_action(f"Open {top['ward']}", "view_ward", ward_id=top.get("brief", {}).get("scope", {}).get("ward_id"), ward_name=top["ward"], district=scope.get("district"))]
        elif intent == "OUT_OF_SCOPE":
            answer = "The Intelligence Copilot is designed for the Crime Intel Suite analytical dataset. I can help with risk, trends, alerts, hotspots, incidents, offenders, networks, and intelligence briefs."
        else:
            answer = "The Intelligence Copilot is designed for this crime analytics dataset. Ask about risk, trends, alerts, hotspots, incidents, offenders, networks, or the current intelligence brief."
        return answer, [a for a in actions if a]


def _call_llm(message: str, evidence: dict, history: list[dict], lang: str = "en") -> str | None:
    key = os.getenv("OPENAI_API_KEY")
    if not key: return None

    lang_prompt = " Respond entirely in English."
    if lang == "kn":
        lang_prompt = " CRITICAL INSTRUCTION: Respond ENTIRELY in Kannada (ಕನ್ನಡ) language and script. Output all explanations, insights, and summaries in natural, professional Kannada."
    elif lang == "hi":
        lang_prompt = " CRITICAL INSTRUCTION: Respond ENTIRELY in Hindi (हिन्दी) Devanagari script. Output all explanations, insights, and summaries in natural, professional Hindi."

    body = {"model": os.getenv("OPENAI_MODEL", "llama-3.3-70b-versatile"), "messages": [
        {"role": "system", "content": f"You are Intelligence Copilot for Crime Intel Suite. Answer all user questions helpfully. For dashboard questions, analyse the supplied evidence before answering: state the most important finding, connect relevant risk/trend/alert signals, distinguish observed facts from predictions, explain uncertainty or data limitations, and suggest safe analytical next steps when useful. Use only the supplied structured evidence and never invent numbers, people, locations, causes, certainty, or enforcement recommendations. For general questions, give a concise, factual answer and make clear that it is not dashboard evidence. Format the response as Markdown, rendered in a chat panel — match structure to the question: a single fact or a question about one specific item (e.g. \"which X has the highest Y\") gets a short heading plus a compact bullet list of that item's own fields, not a table; a request to compare multiple items or rank several of them is the only case that should use a Markdown table; a request to analyze/summarize a broader scope gets a brief structured summary (a short paragraph and/or a few bullets, optionally one small table of the top few items) rather than dumping every available field. Never emit raw table syntax outside an actual Markdown table, and do not pad a simple answer with an unnecessary table just because the evidence contains a list. {lang_prompt}"},
        *[{"role": x.get("role", "user"), "content": str(x.get("content", ""))[:1200]} for x in history[-8:]],
        {"role": "user", "content": f"Evidence context (authoritative):\n{json.dumps(evidence, ensure_ascii=False, default=str)[:10000]}\n\nQuestion: {message}"},
    ], "temperature": 0.1, "max_tokens": 400}
    base_url = os.getenv('OPENAI_BASE_URL', 'https://api.groq.com/openai/v1')
    try:
        response = requests.post(f"{base_url}/chat/completions", headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json", "User-Agent": "CrimeIntelSuite/1.0"}, json=body, timeout=20)
        if response.status_code >= 400:
            # Never hide this behind the deterministic fallback silently \u2014 a
            # bad model name / auth / rate-limit error looks identical to
            # "insufficient data" from the user's seat unless it's logged.
            logger.warning("Copilot LLM call failed: HTTP %s from %s (model=%s): %s",
                            response.status_code, base_url, body["model"], response.text[:300])
            return None
        answer = response.json()["choices"][0]["message"]["content"].strip()
        # Models occasionally ignore a language instruction.  Do not leak that
        # response into a Kannada/Hindi conversation; the localized fallback is
        # safer and consistently readable.
        if lang == "kn" and not re.search(r"[\u0C80-\u0CFF]", answer):
            logger.info("Copilot LLM response ignored Kannada instruction; using localized fallback instead.")
            return None
        if lang == "hi" and not re.search(r"[\u0900-\u097F]", answer):
            logger.info("Copilot LLM response ignored Hindi instruction; using localized fallback instead.")
            return None
        return answer
    except Exception as e:
        logger.warning("Copilot LLM call raised %s: %s", type(e).__name__, e)
        return None


def _evidence_status(evidence: dict) -> str | None:
    """Pull a representative status/data-sufficiency flag for debug logging."""
    for key in ("overview", "brief", "risk", "trend"):
        v = evidence.get(key)
        if isinstance(v, dict) and "status" in v:
            return v["status"]
    return None


def answer_copilot(db: Session, message: str, context: dict | None = None, history: list[dict] | None = None) -> dict:
    context = context or {}; history = history or []
    lang = context.get("language") if context.get("language") in {"en", "kn", "hi"} else "en"
    evidence = build_evidence_context(db, message, context)
    if evidence["intent"] == "COMPARE":
        district, _, crime = _scope(db, message, context); wards = _find_compare_wards(db, message, district)
        if len(wards) < 2:
            no_compare_msg = "ನೋಡಲು ಸಾಧ್ಯವಾಗಿಲ್ಲ." if lang == "kn" else "तुलना के लिए दो वार्ड की आवश्यकता है।" if lang == "hi" else "I could not reliably identify two wards to compare."
            return {"answer": no_compare_msg, "evidence": [], "actions": [], "scope": {"district": district, "ward_id": None}, "sources": []}
        briefs = [_brief_context(db, district, w.id, crime, *_dates(context), int(context.get("prediction_horizon") or 14), context.get("granularity") or "weekly") for w in wards]
        evidence.update({"comparison": [{"ward": w.name, "brief": _compact(b)} for w, b in zip(wards, briefs)], "sources": ["Ward Intelligence Briefs"]})
    fallback, actions = _fallback(message, evidence, db, lang=lang)
    llm_answer = _call_llm(message, evidence, history, lang=lang)
    answer = llm_answer or fallback
    logger.info(
        "copilot request: question=%r lang=%s intent=%s district=%s ward_id=%s crime_type=%s "
        "sources=%s evidence_status=%s used_llm=%s",
        message[:120], lang, evidence["intent"], evidence["scope"].get("district"),
        evidence["scope"].get("ward_id"), evidence["scope"].get("crime_type"),
        evidence.get("sources"), _evidence_status(evidence), llm_answer is not None,
    )
    source_names = {
        "kn": {"Intelligence Brief": "ಗುಪ್ತಚರ ಸಾರಾಂಶ", "Predictive Risk": "ಮುನ್ಸೂಚನಾ ಅಪಾಯ", "Trend Analytics": "ಪ್ರವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ", "Intelligence Alerts": "ಗುಪ್ತಚರ ಎಚ್ಚರಿಕೆಗಳು", "Hotspot Analytics": "ಹಾಟ್‌ಸ್ಪಾಟ್ ವಿಶ್ಲೇಷಣೆ", "Network Analytics": "ಜಾಲ ವಿಶ್ಲೇಷಣೆ", "Repeat Offender Analytics": "ಪುನರಾವರ್ತಿತ ಅಪರಾಧಿ ವಿಶ್ಲೇಷಣೆ", "Incident Records": "ಘಟನೆ ದಾಖಲೆಗಳು", "Ward Intelligence Briefs": "ವಾರ್ಡ್ ಗುಪ್ತಚರ ಸಾರಾಂಶಗಳು"},
        "hi": {"Intelligence Brief": "इंटेलिजेंस ब्रीफ", "Predictive Risk": "पूर्वानुमानित जोखिम", "Trend Analytics": "ट्रेंड विश्लेषण", "Intelligence Alerts": "इंटेलिजेंस अलर्ट", "Hotspot Analytics": "हॉटस्पॉट विश्लेषण", "Network Analytics": "नेटवर्क विश्लेषण", "Repeat Offender Analytics": "दोहराने वाले अपराधी विश्लेषण", "Incident Records": "घटना रिकॉर्ड", "Ward Intelligence Briefs": "वार्ड इंटेलिजेंस ब्रीफ"},
    }
    sources = [source_names.get(lang, {}).get(source, source) for source in evidence.get("sources", [])]
    return {"answer": answer, "evidence": _evidence_rows(evidence, lang=lang), "actions": [a for a in actions if a.get("action") in SUPPORTED_ACTIONS], "scope": evidence["scope"], "sources": sources, "intent": evidence["intent"]}


def _evidence_rows(evidence: dict, lang: str = "en") -> list[dict]:
    rows = []
    lbl_risk = "ಅಪಾಯದ ಮಟ್ಟ" if lang == "kn" else "जोखिम स्तर" if lang == "hi" else "Predictive risk"
    lbl_trend = "ಪ್ರವೃತ್ತಿ" if lang == "kn" else "ट्रेंड" if lang == "hi" else "Trend"
    lbl_alerts = "ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು" if lang == "kn" else "सक्रिय अलर्ट" if lang == "hi" else "Active alerts"
    lbl_hotspots = "ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು" if lang == "kn" else "हॉटस्पॉट" if lang == "hi" else "Hotspots"
    lbl_network = "ಅಪರಾಧಿ ಜಾಲ" if lang == "kn" else "नेटवर्क" if lang == "hi" else "Network"

    b = evidence.get("brief") or {}
    if b.get("predictive_risk", {}).get("risk_score") is not None:
        p = b["predictive_risk"]; rows.append({"label": lbl_risk, "value": f"{p['risk_score']}/100 — {_localized_level(p.get('risk_level'), lang)}"})
    if b.get("key_development"):
        t = b["key_development"]; rows.append({"label": lbl_trend, "value": f"{t.get('crime_type') or 'Crime'} {t.get('change_percent')}% — {t.get('severity')}"})
    if b.get("alerts", {}).get("total") is not None: rows.append({"label": lbl_alerts, "value": str(b["alerts"]["total"])})
    if b.get("hotspots", {}).get("count") is not None: rows.append({"label": lbl_hotspots, "value": str(b["hotspots"]["count"])})
    if evidence.get("risk", {}).get("predictions"):
        p = evidence["risk"]["predictions"][0]
        no_data = "ಸಾಕಷ್ಟು ಮಾಹಿತಿ ಇಲ್ಲ" if lang == "kn" else "पर्याप्त डेटा नहीं" if lang == "hi" else "Insufficient data"
        rows.append({"label": lbl_risk, "value": no_data if p.get("insufficient_data") else f"{p.get('risk_score')}/100 — {_localized_level(p.get('risk_level'), lang)}"})
    if evidence.get("trend"):
        t = evidence["trend"]; candidates = t.get("anomalies") or t.get("top_emerging_trends") or []
        top = max(candidates, key=lambda x: abs(x.get("percentage_change", x.get("change_percent", 0)) or 0), default=None)
        if top:
            crime_label = top.get('crime_type') or ("ಅಪರಾಧ" if lang == "kn" else "अपराध" if lang == "hi" else "Crime")
            rows.append({"label": lbl_trend, "value": f"{crime_label} {top.get('percentage_change', top.get('change_percent', '—'))}% — {_localized_level(top.get('severity') or top.get('direction'), lang)}"})
    if evidence.get("hotspots"):
        h = evidence["hotspots"]; rows.append({"label": lbl_hotspots, "value": f"{h.get('n_clusters', 0)} clusters from {h.get('n_incidents', 0)} incidents"})
    if evidence.get("alerts", {}).get("summary"):
        s = evidence["alerts"]["summary"]; rows.append({"label": lbl_alerts, "value": f"{s.get('total', 0)} total; {s.get('critical', 0)} critical"})
    if evidence.get("network", {}).get("summary"):
        s = evidence["network"]["summary"]; rows.append({"label": lbl_network, "value": f"{s.get('n_nodes', 0)} offenders; {s.get('n_communities', 0)} groups"})
    if evidence.get("comparison"):
        for item in evidence["comparison"][:2]:
            b = item.get("brief", {}); rows.append({"label": item.get("ward", "Ward"), "value": f"{b.get('priority', {}).get('score', '—')}/100 {b.get('priority', {}).get('level', 'unavailable')} · {b.get('summary', {}).get('incidents', b.get('recent_incidents', '—'))} incidents"})
    return rows[:5]
