import React from 'react';

const LEVEL = { CRITICAL: 'bg-rose-500/20 text-rose-200 border-rose-400/40', HIGH: 'bg-orange-500/20 text-orange-200 border-orange-400/40', MEDIUM: 'bg-amber-500/20 text-amber-200 border-amber-400/40', LOW: 'bg-emerald-500/20 text-emerald-200 border-emerald-400/40' };
function Card({ title, children, action }) { return <section className="brief-card glass-card p-4 sm:p-5" data-card-title={title}><div className="flex items-center justify-between gap-3 mb-3"><h3 className="text-xs uppercase tracking-wider font-semibold text-slate-400">{title}</h3>{action}</div>{children}</section>; }

export default function IntelligenceBrief({ brief, loading, error, onNavigate, onRefresh }) {
  if (!brief && !loading) return <div className="glass-card p-10 text-center text-slate-300">Select a district to generate an Intelligence Brief.</div>;
  if (loading) return <div className="glass-card p-10 flex justify-center"><div className="w-8 h-8 border-2 border-primary-500/30 border-t-primary-400 rounded-full animate-spin" /></div>;
  if (error || brief?.status !== 'ok') return <div className="glass-card p-8 text-center text-rose-300">{error || brief?.message || 'Unable to generate the Intelligence Brief.'}</div>;
  const b = brief, risk = b.predictive_risk, a = b.alerts || {}, go = (x, item) => onNavigate?.(x, item);
  return <div className="intelligence-brief space-y-4 view-transition">
    <div className="brief-hero flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-primary-300">{b.scope.type} intelligence brief</p><h2 className="text-2xl font-bold text-white mt-1">{b.scope.name}</h2><p className="text-xs text-slate-500 mt-1">Generated from data through {b.analysis_window?.to ? new Date(b.analysis_window.to).toLocaleDateString('en-IN') : 'the available dataset'}</p></div><div className="flex items-center gap-3"><button onClick={onRefresh} className="text-xs text-primary-300 hover:text-white">Refresh Brief</button><div className={`brief-priority rounded-xl border px-4 py-2 text-center ${LEVEL[b.priority.level] || LEVEL.MEDIUM}`}><p className="text-[10px] uppercase tracking-widest">Priority</p><p className="text-xl font-bold">{b.priority.level}</p><p className="text-[10px] opacity-75">{b.priority.score}/100</p></div></div></div>
    <Card title="Key development"><p className="text-lg font-semibold text-white">{b.headline}</p>{b.key_development ? <p className="text-sm text-slate-300 mt-2">{b.key_development.crime_type || 'Crime'} is <span className="text-primary-300 font-semibold">{b.key_development.direction}</span> by {Math.abs(b.key_development.change_percent ?? 0).toFixed(0)}% versus its historical baseline.</p> : <p className="text-sm text-slate-500 italic mt-2">No significant trend anomaly detected.</p>}</Card>
    <Card title="Why this matters"><ul className="space-y-2">{(b.why_it_matters || []).length ? b.why_it_matters.map((x) => <li key={x} className="text-sm text-slate-300 flex gap-2"><span className="text-primary-300">•</span>{x}</li>) : <li className="text-sm text-slate-500 italic">No additional elevated signals detected.</li>}</ul></Card>
    {b.highest_priority_ward && <Card title="Highest priority ward" action={<button className="text-xs text-primary-300 hover:text-white" onClick={() => go('view_ward', b.highest_priority_ward)}>Open Ward Intelligence →</button>}><p className="text-base font-semibold text-white">{b.highest_priority_ward.ward_name}</p><p className="text-xs text-slate-400 mt-1">Risk: {b.highest_priority_ward.risk_level?.toUpperCase() || 'Unavailable'} · Alerts: {b.highest_priority_ward.active_alerts ?? 0} · Hotspots: {b.highest_priority_ward.hotspots ?? 0}</p></Card>}
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Card title="Predictive outlook" action={<button className="text-xs text-primary-300" onClick={() => go('view_risk')}>View risk →</button>}>{risk?.risk_score != null ? <><p className="text-2xl font-bold text-white">{risk.risk_score}/100 <span className="text-sm text-primary-300">{risk.risk_level?.toUpperCase()}</span></p><p className="text-xs text-slate-400 mt-1">Next {risk.prediction_horizon_days} days{risk.predicted_incidents != null ? ` · Expected incidents: ${risk.predicted_incidents}` : ''}{risk.confidence != null ? ` · Confidence: ${Math.round(risk.confidence * 100)}%` : ''}</p></> : <p className="text-sm text-slate-500 italic">Predictive outlook unavailable — insufficient historical data.</p>}</Card><Card title="Active alerts" action={<button className="text-xs text-primary-300" onClick={() => go('view_alerts')}>View all →</button>}>{a.total ? <><p className="text-2xl font-bold text-white">{a.total}</p><p className="text-xs text-slate-400 mt-1">{a.critical || 0} Critical · {a.high || 0} High · {a.medium || 0} Medium · {a.low || 0} Low</p></> : <p className="text-sm text-slate-500 italic">No active intelligence alerts.</p>}</Card><Card title="Crime pattern"><p className="text-sm text-slate-300">Dominant crime: <span className="text-white font-medium">{b.crime_pattern?.dominant_crime_type || 'Not available'}</span></p><p className="text-sm text-slate-400 mt-2">Most active: {b.time_pattern?.most_active_day || 'Not available'} · {b.time_pattern?.most_active_hour_range || 'Not available'}</p></Card><Card title="Hotspots" action={<button className="text-xs text-primary-300" onClick={() => go('view_hotspots')}>View hotspots →</button>}><p className="text-2xl font-bold text-white">{b.hotspots?.count || 0}</p><p className="text-xs text-slate-400 mt-1">{b.hotspots?.count ? 'Active clusters in this scope' : 'No active hotspot detected for this scope.'}</p></Card></div>
    <Card title="Offender & network signal" action={<button className="text-xs text-primary-300" onClick={() => go('view_network')}>Open network →</button>}><p className="text-sm text-slate-300"><span className="text-white font-semibold">{b.repeat_offenders?.count || 0}</span> repeat offenders · <span className="text-white font-semibold">{b.network?.linked_offenders || 0}</span> linked offenders · <span className="text-white font-semibold">{b.network?.communities || 0}</span> communities</p></Card>
    <Card title="Analytical follow-ups"><div className="grid sm:grid-cols-2 gap-2">{(b.analytical_followups || []).map((item) => <button key={`${item.action}:${item.ward_id ?? item.label}`} onClick={() => go(item.action, item)} className="text-left rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-sm text-slate-300 hover:border-primary-400/40 hover:text-white">{item.label} <span className="text-primary-300">→</span></button>)}</div></Card><p className="text-[11px] text-slate-600 text-center">{b.responsible_analytics}</p>
  </div>;
}
